package view;

import java.awt.Color;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.Usuario;
import view.proyecto.ContratoGUI;

/**
 *
 * @author Esdras
 */
public class PrincipalGUI extends javax.swing.JFrame {

    /**
     * Creates new form JFPrincipal
     */
    public PrincipalGUI(Usuario oUsuario) {
        initComponents();
    
        setVisible(true);
        
        URL url = getClass().getResource("/Iconos/IconoGestorVial1.png");
        ImageIcon img = new ImageIcon(url);
        setIconImage(img.getImage());
        
        setTitle("GESTOR DE CONSERVACIÓN VIAL v.2 - " +"Empresa x"+"\n");
        setBienvenida("BIENVENIDO, "+oUsuario.getUserUser().toUpperCase());
        menuBarGECOVI.setBackground(Color.darkGray);
        setExtendedState(MAXIMIZED_BOTH);      
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        jLabelNombreUsuario = new javax.swing.JLabel();
        menuBarGECOVI = new javax.swing.JMenuBar();
        jMenuConfiguracion = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuMantenimiento = new javax.swing.JMenu();
        jMenuItemMantCargoPersonal = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuProyecto = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        saveAsMenuItem1 = new javax.swing.JMenuItem();
        jMenuActiviadad = new javax.swing.JMenu();
        contentMenuItem1 = new javax.swing.JMenuItem();
        jMenuPersonal = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItemCargo = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuMantenimientoPersonal = new javax.swing.JMenu();
        jMenuItemMantCargo = new javax.swing.JMenuItem();
        jMenuEquipoMecanico = new javax.swing.JMenu();
        jMenuMaterial = new javax.swing.JMenu();
        jMenuProducto = new javax.swing.JMenu();
        jMenuItemProducto = new javax.swing.JMenuItem();
        jMenuItemMarca = new javax.swing.JMenuItem();
        jMenuItemUnidadMedida = new javax.swing.JMenuItem();
        jMenuItemTipo = new javax.swing.JMenuItem();
        MenuMantenimiento = new javax.swing.JMenu();
        MenuItemProveedor = new javax.swing.JMenuItem();
        exitMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuUsuario = new javax.swing.JMenu();
        jMenuItemNuevo = new javax.swing.JMenuItem();
        jMenuItemModificar = new javax.swing.JMenuItem();
        jMenuItemEliminar = new javax.swing.JMenuItem();
        jMenuItemConsultar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jLabelNombreUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelNombreUsuario.setForeground(new java.awt.Color(51, 0, 153));
        jLabelNombreUsuario.setText("Bienvenido(a) Usuario");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelNombreUsuario)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNombreUsuario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuConfiguracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Config.png"))); // NOI18N
        jMenuConfiguracion.setText("Configuración Inicial");

        jMenuItem2.setText("Datos de la Empresa");
        jMenuConfiguracion.add(jMenuItem2);

        jMenuItem6.setText("Aperturar comprobantes");
        jMenuConfiguracion.add(jMenuItem6);

        jMenuItem1.setText("Impuesto y leyes sociales");
        jMenuConfiguracion.add(jMenuItem1);

        jMenuItem7.setText("Restore");
        jMenuConfiguracion.add(jMenuItem7);

        jMenuItem9.setText("Backup");
        jMenuConfiguracion.add(jMenuItem9);

        jMenuMantenimiento.setText("Mantenimiento");

        jMenuItemMantCargoPersonal.setText("Cargo de personal");
        jMenuItemMantCargoPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMantCargoPersonalActionPerformed(evt);
            }
        });
        jMenuMantenimiento.add(jMenuItemMantCargoPersonal);

        jMenuItem14.setText("jMenuItem14");
        jMenuMantenimiento.add(jMenuItem14);

        jMenuItem15.setText("jMenuItem15");
        jMenuMantenimiento.add(jMenuItem15);

        jMenuItem16.setText("jMenuItem16");
        jMenuMantenimiento.add(jMenuItem16);

        jMenuItem17.setText("jMenuItem17");
        jMenuMantenimiento.add(jMenuItem17);

        jMenuConfiguracion.add(jMenuMantenimiento);

        menuBarGECOVI.add(jMenuConfiguracion);

        jMenuProyecto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/MenuPrincipal/Proyecto.png"))); // NOI18N
        jMenuProyecto.setText("Proyecto");

        jMenuItem8.setText("Contratos");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenuProyecto.add(jMenuItem8);

        jMenuItem3.setText("Tramos");
        jMenuProyecto.add(jMenuItem3);

        jMenuItem4.setText("Sectores");
        jMenuProyecto.add(jMenuItem4);

        jMenuItem5.setText("Actividades");
        jMenuProyecto.add(jMenuItem5);

        jMenu5.setText("Venta al Contado");

        saveAsMenuItem1.setMnemonic('a');
        saveAsMenuItem1.setText("Cliente");
        jMenu5.add(saveAsMenuItem1);

        jMenuProyecto.add(jMenu5);

        menuBarGECOVI.add(jMenuProyecto);

        jMenuActiviadad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/MenuPrincipal/Actividad.png"))); // NOI18N
        jMenuActiviadad.setText("Actividad");

        contentMenuItem1.setMnemonic('c');
        contentMenuItem1.setText("Registrar actividad");
        contentMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contentMenuItem1ActionPerformed(evt);
            }
        });
        jMenuActiviadad.add(contentMenuItem1);

        menuBarGECOVI.add(jMenuActiviadad);

        jMenuPersonal.setBackground(new java.awt.Color(51, 255, 0));
        jMenuPersonal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/MenuPrincipal/Personal.png"))); // NOI18N
        jMenuPersonal.setMnemonic('h');
        jMenuPersonal.setText("Personal");

        jMenuItem12.setText("Gestionar Personal");
        jMenuPersonal.add(jMenuItem12);

        jMenuItemCargo.setText("Cargo");
        jMenuItemCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCargoActionPerformed(evt);
            }
        });
        jMenuPersonal.add(jMenuItemCargo);

        jMenuItem11.setText("Cargo1");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenuPersonal.add(jMenuItem11);

        jMenuMantenimientoPersonal.setText("Mantenimiento");

        jMenuItemMantCargo.setText("Cargo");
        jMenuItemMantCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMantCargoActionPerformed(evt);
            }
        });
        jMenuMantenimientoPersonal.add(jMenuItemMantCargo);

        jMenuPersonal.add(jMenuMantenimientoPersonal);

        menuBarGECOVI.add(jMenuPersonal);

        jMenuEquipoMecanico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/MenuPrincipal/Equipo Mecanico.png"))); // NOI18N
        jMenuEquipoMecanico.setText("Equipo mecánico");
        menuBarGECOVI.add(jMenuEquipoMecanico);

        jMenuMaterial.setBackground(new java.awt.Color(51, 255, 0));
        jMenuMaterial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/MenuPrincipal/Material utilizado.png"))); // NOI18N
        jMenuMaterial.setMnemonic('e');
        jMenuMaterial.setText("Material");

        jMenuProducto.setText("Material");

        jMenuItemProducto.setText("Material");
        jMenuProducto.add(jMenuItemProducto);

        jMenuItemMarca.setText("Marca");
        jMenuProducto.add(jMenuItemMarca);

        jMenuItemUnidadMedida.setText("Unidad de Medida");
        jMenuProducto.add(jMenuItemUnidadMedida);

        jMenuItemTipo.setText("Tipo de Material");
        jMenuProducto.add(jMenuItemTipo);

        jMenuMaterial.add(jMenuProducto);

        MenuMantenimiento.setBackground(new java.awt.Color(51, 255, 0));
        MenuMantenimiento.setMnemonic('f');
        MenuMantenimiento.setText("Compra al Contado");

        MenuItemProveedor.setMnemonic('P');
        MenuItemProveedor.setText("Proveedor");
        MenuMantenimiento.add(MenuItemProveedor);

        exitMenuItem1.setMnemonic('x');
        exitMenuItem1.setText("Exit");
        MenuMantenimiento.add(exitMenuItem1);

        jMenuMaterial.add(MenuMantenimiento);

        jMenuItem10.setText("Controlar Materiales");
        jMenuMaterial.add(jMenuItem10);

        menuBarGECOVI.add(jMenuMaterial);

        jMenuUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/MenuPrincipal/Gestor Usuario.png"))); // NOI18N
        jMenuUsuario.setText("Usuario");

        jMenuItemNuevo.setText("Nuevo usuario");
        jMenuUsuario.add(jMenuItemNuevo);

        jMenuItemModificar.setText("Modificar permiso");
        jMenuUsuario.add(jMenuItemModificar);

        jMenuItemEliminar.setText("Eliminar Usuario");
        jMenuUsuario.add(jMenuItemEliminar);

        jMenuItemConsultar.setText("Consultar Usuario");
        jMenuUsuario.add(jMenuItemConsultar);

        menuBarGECOVI.add(jMenuUsuario);

        setJMenuBar(menuBarGECOVI);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 898, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCargoActionPerformed
        
       
    }//GEN-LAST:event_jMenuItemCargoActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItemMantCargoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItemMantCargoActionPerformed
    {//GEN-HEADEREND:event_jMenuItemMantCargoActionPerformed
        
    }//GEN-LAST:event_jMenuItemMantCargoActionPerformed

    private void jMenuItemMantCargoPersonalActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItemMantCargoPersonalActionPerformed
    {//GEN-HEADEREND:event_jMenuItemMantCargoPersonalActionPerformed
//        String x=JIFCargoGUI.x;
//        if (x==null)
//        {
//            JIFCargoGUI objJIFCargoGUI= new JIFCargoGUI();
//            desktopPane.add(objJIFCargoGUI);
//            desktopPane.moveToFront(objJIFCargoGUI);
//        }
//        else
//        {
//            JOptionPane.showMessageDialog(rootPane, "Ventana abierta de Mantenimiento de Cargos");
//        }
    }//GEN-LAST:event_jMenuItemMantCargoPersonalActionPerformed

    private void contentMenuItem1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_contentMenuItem1ActionPerformed
    {//GEN-HEADEREND:event_contentMenuItem1ActionPerformed
//        String x=JIFRegistrarActividadGUI.x;
//        if (x==null)
//        {
//            JIFRegistrarActividadGUI objRegAct= new JIFRegistrarActividadGUI();
//            desktopPane.add(objRegAct);
//            desktopPane.moveToFront(objRegAct);
//        }
//        else
//        {
//            JOptionPane.showMessageDialog(rootPane, "Ventana abierta de Registro de Actividad");
//        }
    }//GEN-LAST:event_contentMenuItem1ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        
        new ContratoGUI().setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new JFPrincipalGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuItemProveedor;
    private javax.swing.JMenu MenuMantenimiento;
    private javax.swing.JMenuItem contentMenuItem1;
    public static javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem1;
    private javax.swing.JLabel jLabelNombreUsuario;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenuActiviadad;
    private javax.swing.JMenu jMenuConfiguracion;
    private javax.swing.JMenu jMenuEquipoMecanico;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem jMenuItemCargo;
    private javax.swing.JMenuItem jMenuItemConsultar;
    private javax.swing.JMenuItem jMenuItemEliminar;
    private javax.swing.JMenuItem jMenuItemMantCargo;
    private javax.swing.JMenuItem jMenuItemMantCargoPersonal;
    private javax.swing.JMenuItem jMenuItemMarca;
    private javax.swing.JMenuItem jMenuItemModificar;
    private javax.swing.JMenuItem jMenuItemNuevo;
    private javax.swing.JMenuItem jMenuItemProducto;
    private javax.swing.JMenuItem jMenuItemTipo;
    private javax.swing.JMenuItem jMenuItemUnidadMedida;
    private javax.swing.JMenu jMenuMantenimiento;
    private javax.swing.JMenu jMenuMantenimientoPersonal;
    private javax.swing.JMenu jMenuMaterial;
    private javax.swing.JMenu jMenuPersonal;
    private javax.swing.JMenu jMenuProducto;
    private javax.swing.JMenu jMenuProyecto;
    private javax.swing.JMenu jMenuUsuario;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenuBar menuBarGECOVI;
    private javax.swing.JMenuItem saveAsMenuItem1;
    // End of variables declaration//GEN-END:variables

    private void setBienvenida(String string) {
        jLabelNombreUsuario.setText(string);
    }

}
